# Generated by Django 5.2.3 on 2025-07-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_tickethistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickethistory',
            name='new_priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='previous_priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='new_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], max_length=20, null=True),
        ),
    ]
