# Generated by Django 5.2.3 on 2025-07-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_tickethistory_new_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='comment_attachments/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='ticket_attachments/'),
        ),
    ]
